import React, { useState } from 'react';
import { ArrowLeft, TrendingUp, AlertTriangle, CheckCircle2, Clock, Share2, Copy, Check } from 'lucide-react';
import { createShareLink } from '../logic/share.js';
import { UrgencyBadge, ModeBadge } from '../components/InsightCard.jsx';
import { MODES } from '../logic/ai.js';

// ─── Share helpers ────────────────────────────────────────────────────────────
function ShareBar({ insight }) {
  const [copied,   setCopied]   = useState(false);
  const [shareUrl, setShareUrl] = useState('');
  const [creating, setCreating] = useState(false);

  // Create short URL once on mount
  React.useEffect(() => {
    setCreating(true);
    createShareLink(insight)
      .then(url => { setShareUrl(url); setCreating(false); })
      .catch(() => setCreating(false));
  }, []);

  const copyLink = async () => {
    if (!shareUrl) return;
    try { await navigator.clipboard.writeText(shareUrl); }
    catch {
      const el = document.createElement('textarea');
      el.value = shareUrl;
      document.body.appendChild(el); el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Strip <cite index="...">text</cite> tags that Claude adds from web search
  const clean = (t) => (t || '')
    .replace(/<cite[^>]*>(.*?)<\/cite>/gs, '$1')
    .replace(/<[^>]+>/g, '')
    .trim();

  const waText = [
    `${MODES[insight?.mode]?.icon || '🧠'} *${clean(insight?.title)}*`,
    `🔴 Urgency: ${(insight?.urgency || '').toUpperCase()} · ${clean(insight?.urgency_timeframe)}`,
    `📡 Signal\n${clean(insight?.signal)}`,
    insight?.context  ? `💡 Why it matters\n${clean(insight?.context)}` : null,
    insight?.actions?.length ? `⚡ Top Actions\n${insight.actions.slice(0,2).map((a,i) => `${i+1}. ${clean(a.action)} (${clean(a.owner)}, ${clean(a.timeline)})`).join('\n')}` : null,
    `—\nGenerated by UDIE · Unified Decision Intelligence Engine\n${shareUrl}`,
  ].filter(Boolean).join('\n\n');

  const shareWhatsApp = () => {
    if (!shareUrl) return;
    window.open(`https://wa.me/?text=${encodeURIComponent(waText)}`, '_blank');
  };

  const shareNative = async () => {
    if (!shareUrl || !navigator.share) return;
    try { await navigator.share({ title: insight?.title, text: waText, url: shareUrl }); } catch {}
  };

  return (
    <div style={{ display:'flex', gap:8, marginTop:4, marginBottom:8 }}>
      {/* Copy link */}
      <button onClick={copyLink}
        style={{ flex:1, display:'flex', alignItems:'center', justifyContent:'center', gap:7, padding:'11px 14px', background: copied ? 'var(--green-bg)' : 'var(--surface2)', border:`1.5px solid ${copied ? 'var(--green)' : 'var(--border2)'}`, borderRadius:'var(--r-md)', color: copied ? 'var(--green)' : 'var(--text2)', fontSize:13, fontWeight:600, cursor:'pointer', transition:'all .2s', fontFamily:'var(--font-body)' }}>
        {copied ? <Check size={15}/> : <Copy size={15}/>}
        {copied ? 'Copied!' : 'Copy Link'}
      </button>

      {/* WhatsApp */}
      <button onClick={shareWhatsApp}
        style={{ flex:1, display:'flex', alignItems:'center', justifyContent:'center', gap:7, padding:'11px 14px', background:'rgba(37,211,102,0.10)', border:'1.5px solid rgba(37,211,102,0.30)', borderRadius:'var(--r-md)', color:'#25D366', fontSize:13, fontWeight:600, cursor:'pointer', fontFamily:'var(--font-body)' }}>
        <svg width="15" height="15" viewBox="0 0 24 24" fill="#25D366">
          <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
        </svg>
        WhatsApp
      </button>

      {/* Native share (mobile) */}
      {typeof navigator !== 'undefined' && navigator.share && (
        <button onClick={shareNative}
          style={{ width:44, display:'flex', alignItems:'center', justifyContent:'center', padding:'11px', background:'var(--surface2)', border:'1.5px solid var(--border2)', borderRadius:'var(--r-md)', color:'var(--text2)', cursor:'pointer', flexShrink:0 }}>
          <Share2 size={15}/>
        </button>
      )}
    </div>
  );
}

// ─── Main screen ──────────────────────────────────────────────────────────────
export default function InsightDetailScreen({ navigate, insight }) {
  if (!insight) { navigate('home'); return null; }

  const mode  = MODES[insight.mode];
  const isRisk = insight.opportunity_or_risk === 'risk';
  const isOpp  = insight.opportunity_or_risk === 'opportunity';
  const urgencyColors = { high:'var(--red)', medium:'var(--amber)', low:'var(--green)' };
  const accentColor = urgencyColors[insight.urgency] || 'var(--blue-light)';

  return (
    <div className="screen">
      <div className="header">
        <button className="header-back" onClick={() => navigate(-1)}>
          <ArrowLeft size={16}/>
        </button>
        <div style={{ flex:1, minWidth:0 }}>
          <div className="header-title" style={{ fontSize:15 }}>Intelligence Report</div>
          <div className="header-sub">{mode ? `${mode.icon} ${mode.label}` : 'Full Analysis'}</div>
        </div>
        <UrgencyBadge urgency={insight.urgency}/>
      </div>

      <div className="content">
        {/* Title block */}
        <div style={{ background:'var(--surface)', border:`1px solid var(--border)`, borderLeft:`4px solid ${accentColor}`, borderRadius:'var(--r-xl)', padding:18, marginBottom:14 }}>
          <div style={{ fontSize:20, fontWeight:700, letterSpacing:'-.03em', lineHeight:1.2, marginBottom:10, color:'var(--text)' }}>
            {insight.title}
          </div>
          <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
            <UrgencyBadge urgency={insight.urgency}/>
            {insight.mode && <ModeBadge mode={insight.mode}/>}
            {insight.opportunity_or_risk && (
              <span className="badge" style={{ background: isOpp ? 'var(--green-bg)' : isRisk ? 'var(--red-bg)' : 'var(--blue-bg)', color: isOpp ? 'var(--green)' : isRisk ? 'var(--red)' : 'var(--blue-light)', border:'none' }}>
                {isOpp ? '📈 Opportunity' : isRisk ? '⚠️ Risk' : '⚡ Mixed'}
              </span>
            )}
          </div>
        </div>

        {/* Share bar — prominent, right after the title */}
        <ShareBar insight={insight}/>

        {/* Signal */}
        <div className="section-title"><TrendingUp size={11} style={{ display:'inline', marginRight:4 }}/>The Signal</div>
        <div className="card">
          <div style={{ fontSize:15, color:'var(--text)', lineHeight:1.6 }}>{insight.signal}</div>
        </div>

        {/* Context */}
        <div className="section-title"><CheckCircle2 size={11} style={{ display:'inline', marginRight:4 }}/>Why It Matters for You</div>
        <div className="card">
          <div style={{ fontSize:14, color:'var(--text2)', lineHeight:1.6 }}>{insight.context}</div>
        </div>

        {/* Impact */}
        {insight.impact?.length > 0 && (
          <>
            <div className="section-title"><AlertTriangle size={11} style={{ display:'inline', marginRight:4 }}/>Business Impact</div>
            <div className="card">
              {insight.impact.map((item, i) => (
                <div key={i} className="impact-item">
                  <div className="impact-dot" style={{ background: i===0 ? accentColor : 'var(--text3)' }}/>
                  <div>{item}</div>
                </div>
              ))}
            </div>
          </>
        )}

        {/* Actions */}
        {insight.actions?.length > 0 && (
          <>
            <div className="section-title">⚡ Recommended Actions</div>
            {insight.actions.map((a, i) => (
              <div key={i} className="action-item">
                <div style={{ display:'flex', gap:12, alignItems:'flex-start' }}>
                  <div className="action-number">{i+1}</div>
                  <div style={{ flex:1 }}>
                    <div style={{ fontWeight:600, fontSize:14, color:'var(--text)', lineHeight:1.4, marginBottom:6 }}>{a.action}</div>
                    <div style={{ display:'flex', gap:8, flexWrap:'wrap' }}>
                      {a.owner && <span style={{ fontSize:11, color:'var(--text3)', background:'var(--surface3)', padding:'2px 8px', borderRadius:999 }}>👤 {a.owner}</span>}
                      {a.timeline && <span style={{ fontSize:11, color:'var(--text3)', background:'var(--surface3)', padding:'2px 8px', borderRadius:999 }}><Clock size={9} style={{ display:'inline', marginRight:3 }}/>{a.timeline}</span>}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </>
        )}

        {/* Supporting signals */}
        {insight.supporting_signals?.length > 0 && (
          <>
            <div className="section-title">📡 Supporting Signals</div>
            <div className="card">
              {insight.supporting_signals.map((s, i) => (
                <div key={i} style={{ display:'flex', gap:10, padding:'8px 0', borderBottom: i < insight.supporting_signals.length-1 ? '1px solid var(--border)' : 'none', fontSize:13, color:'var(--text2)', lineHeight:1.4 }}>
                  <span style={{ color:'var(--text3)' }}>—</span>{s}
                </div>
              ))}
            </div>
          </>
        )}

        {/* Timeframe footer */}
        {insight.urgency_timeframe && (
          <div style={{ display:'flex', alignItems:'center', gap:10, padding:'12px 16px', background:'var(--surface)', border:'1px solid var(--border)', borderRadius:'var(--r-md)', marginTop:4 }}>
            <Clock size={14} style={{ color:accentColor, flexShrink:0 }}/>
            <div>
              <div style={{ fontSize:12, color:'var(--text3)' }}>Time Horizon</div>
              <div style={{ fontSize:14, fontWeight:600, color:'var(--text)', marginTop:2 }}>{insight.urgency_timeframe}</div>
            </div>
            {insight.confidence && (
              <div style={{ marginLeft:'auto', textAlign:'right' }}>
                <div style={{ fontSize:12, color:'var(--text3)' }}>Confidence</div>
                <div style={{ fontSize:14, fontWeight:600, color:'var(--text)', marginTop:2, textTransform:'capitalize' }}>{insight.confidence}</div>
              </div>
            )}
          </div>
        )}

        {/* Share bar again at bottom */}
        <div className="section-title" style={{ marginTop:16 }}>Share This Insight</div>
        <ShareBar insight={insight}/>

        <div style={{ height:24 }}/>
      </div>
    </div>
  );
}
